### ISSUE TITLE
I did not select a textbook when attempting to create a course.  I got this error.

### ISSUE THREAD

**Issue by chasrooney** [bnmnetp/runestone#596]
Traceback (most recent call last):
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/scheduler.py", line 237, in executor
    result = dumps(_function(*args, **vars))
  File "applications/runestone/models/scheduler.py", line 38, in run_sphinx
    conf_file = open(path.join(confdir, 'conf.py'), 'r')
IOError: [Errno 2] No such file or directory: '/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/custom_courses/NNHSCS1x/conf.py'

**Comment by bnmnetp** [comment]
Thanks.

That could be a bit more user friendly.  But, you do need to select a textbook in order for it to work :-)
